collections:
  authors:
    output: true
  tils:
    output: true


highlighter: rouge

# md 파일에 layout 적용할 필요없게 해준다.   
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tils"
    values:
      layout: "til"
  - scope:
      path: ""
    values:
      layout: "default"